### ISSUE TITLE
RCT Design Issue: Hospital specific data - lots of highly correlated covariates

### ISSUE THREAD

**Issue by kmkostka** [ohdsi-studies/Tofacitinib-safety-in-RA#3]
**Error:** In Hospital Charge Datamaster data, there is a large number of "High correlation between covariate(s) and treatment detected." 

Covariate Selection | Description | Concept ID
-- | -- | --
CHADS2 |   | 0
CHADS2VASc |   | 0
index month | 3 | 0
age group | 55-59 | 0
index year | 2018 | 0
condition_era group during day -365   through 0 days relative to index | Arthropathy | 73553
condition_era group during day -30   through 0 days relative to index | Arthropathy | 73553
condition_era group during day -365   through 0 days relative to index | Spinal stenosis | 77079
condition_era group during day -30   through 0 days relative to index | Spinal stenosis | 77079
condition_era group during day -365   through 0 days relative to index | Rheumatoid arthritis | 80809
condition_era group during day -30   through 0 days relative to index | Rheumatoid arthritis | 80809
condition_era group during day -365   through 0 days relative to index | Backache | 134736
condition_era group during day -365   through 0 days relative to index | Spinal cord disease | 135526
condition_era group during day -30   through 0 days relative to index | Spinal cord disease | 135526
condition_era group during day -30   through 0 days relative to index | Hypertensive disorder | 316866
condition_era group during day -30   through 0 days relative to index | Essential hypertension | 320128
condition_era group during day -365   through 0 days relative to index | Peripheral vascular disease | 321052
condition_era group during day -30   through 0 days relative to index | Peripheral vascular disease | 321052
condition_era group during day -365   through 0 days relative to index | Autoimmune disease | 434621
condition_era group during day -30   through 0 days relative to index | Autoimmune disease | 434621
condition_era group during day -365   through 0 days relative to index | Spinal stenosis in cervical region | 436785
condition_era group during day -30   through 0 days relative to index | Spinal stenosis in cervical region | 436785
condition_era group during day -365   through 0 days relative to index | Metabolic syndrome X | 436940
condition_era group during day -30   through 0 days relative to index | Metabolic syndrome X | 436940
condition_era group during day -365   through 0 days relative to index | Cerebral infarction | 443454
condition_era group during day -30   through 0 days relative to index | Cerebral infarction | 443454
condition_era group during day -30   through 0 days relative to index | Vascular disorder | 443784
drug_era group during day -30 through 0   days relative to index | Propofol | 753626
drug_era group during day 0 through 0   days relative to index | Propofol | 753626
drug_era group during day -365 through 0   days relative to index | Haloperidol | 766529
drug_era group during day -30 through 0   days relative to index | Haloperidol | 766529
drug_era group during day 0 through 0   days relative to index | Haloperidol | 766529
drug_era group during day -365 through 0   days relative to index | tizanidine | 778474
drug_era group during day -30 through 0   days relative to index | tizanidine | 778474
drug_era group during day 0 through 0   days relative to index | tizanidine | 778474
drug_era group during day -365 through 0   days relative to index | Scopolamine | 965748
drug_era group during day -30 through 0   days relative to index | Scopolamine | 965748
drug_era group during day 0 through 0   days relative to index | Scopolamine | 965748
drug_era group during day -365 through 0   days relative to index | Sodium Chloride | 967823
drug_era group during day -30 through 0   days relative to index | Sodium Chloride | 967823
drug_era group during day 0 through 0   days relative to index | Sodium Chloride | 967823
drug_era group during day -365 through 0   days relative to index | Spironolactone | 970250
drug_era group during day -30 through 0   days relative to index | Spironolactone | 970250
drug_era group during day 0 through 0   days relative to index | Spironolactone | 970250
drug_era group during day -365 through 0   days relative to index | Tramadol | 1103314
drug_era group during day -30 through 0   days relative to index | Tramadol | 1103314
drug_era group during day 0 through 0   days relative to index | Tramadol | 1103314
drug_era group during day -365 through 0   days relative to index | Aspirin | 1112807
drug_era group during day -30 through 0   days relative to index | Aspirin | 1112807
drug_era group during day 0 through 0   days relative to index | Aspirin | 1112807
drug_era group during day -365 through 0   days relative to index | Hydromorphone | 1126658
drug_era group during day -365 through 0   days relative to index | Phenylephrine | 1135766
drug_era group during day -30 through 0   days relative to index | Phenylephrine | 1135766
drug_era group during day 0 through 0   days relative to index | Phenylephrine | 1135766
drug_era group during day -30 through 0   days relative to index | Fentanyl | 1154029
drug_era group during day 0 through 0   days relative to index | Fentanyl | 1154029
drug_era group during day -365 through 0   days relative to index | Methotrexate | 1305058
drug_era group during day -30 through 0   days relative to index | Methotrexate | 1305058
drug_era group during day 0 through 0   days relative to index | Methotrexate | 1305058
drug_era group during day -365 through 0   days relative to index | Nicardipine | 1318137
drug_era group during day -30 through 0   days relative to index | Nicardipine | 1318137
drug_era group during day 0 through 0   days relative to index | Nicardipine | 1318137
drug_era group during day -365 through 0   days relative to index | clopidogrel | 1322184
drug_era group during day -30 through 0   days relative to index | clopidogrel | 1322184
drug_era group during day 0 through 0   days relative to index | clopidogrel | 1322184
drug_era group during day -365 through 0   days relative to index | Prednisone | 1551099
drug_era group during day -30 through 0   days relative to index | Prednisone | 1551099
drug_era group during day 0 through 0   days relative to index | Prednisone | 1551099
drug_era group during day -365 through 0   days relative to index | Doxycycline | 1738521
drug_era group during day -30 through 0   days relative to index | Doxycycline | 1738521
drug_era group during day 0 through 0   days relative to index | Doxycycline | 1738521
drug_era group during day -365 through 0   days relative to index | Hydroxychloroquine | 1777087
drug_era group during day -30 through 0   days relative to index | Hydroxychloroquine | 1777087
drug_era group during day 0 through 0   days relative to index | Hydroxychloroquine | 1777087
procedure_occurrence during day -30   through 0 days relative to index | Collection of venous blood by venipuncture | 2108115
procedure_occurrence during day -365   through 0 days relative to index | Measurement of post-voiding residual urine and/or bladder   capacity by ultrasound, non-imaging | 2109747
procedure_occurrence during day -30   through 0 days relative to index | Measurement of post-voiding residual urine and/or bladder   capacity by ultrasound, non-imaging | 2109747
procedure_occurrence during day -365   through 0 days relative to index | Transcatheter placement of intravascular stent(s),   intracranial (eg, atherosclerotic stenosis), including balloon angioplasty,   if performed | 2110520
procedure_occurrence during day -30   through 0 days relative to index | Transcatheter placement of intravascular stent(s),   intracranial (eg, atherosclerotic stenosis), including balloon angioplasty,   if performed | 2110520
procedure_occurrence during day -365   through 0 days relative to index | Radiologic examination, chest, 2 views, frontal and lateral | 2211361
measurement during day -365 through 0   days relative to index | Comprehensive metabolic panel This panel must include the   following | 2212093
measurement during day -30 through 0 days   relative to index | Comprehensive metabolic panel This panel must include the   following | 2212093
measurement during day -365 through 0   days relative to index | Urinalysis, by dip stick or tablet reagent for bilirubin,   glucose, hemoglobin, ketones, leukocytes, nitrite, pH, protein, specific   gravity, urobilinogen, any number of these constituents; automated, with   microscopy | 2212166
measurement during day -30 through 0 days   relative to index | Urinalysis, by dip stick or tablet reagent for bilirubin,   glucose, hemoglobin, ketones, leukocytes, nitrite, pH, protein, specific   gravity, urobilinogen, any number of these constituents; automated, with   microscopy | 2212166
measurement during day -365 through 0   days relative to index | Hemoglobin; glycosylated (A1C) | 2212392
measurement during day -30 through 0 days   relative to index | Hemoglobin; glycosylated (A1C) | 2212392
measurement during day -365 through 0   days relative to index | Magnesium | 2212453
measurement during day -30 through 0 days   relative to index | Magnesium | 2212453
measurement during day -365 through 0   days relative to index | Phosphorus inorganic (phosphate) | 2212523
measurement during day -30 through 0 days   relative to index | Phosphorus inorganic (phosphate) | 2212523
measurement during day -365 through 0   days relative to index | Potassium; serum, plasma or whole blood | 2212531
measurement during day -365 through 0   days relative to index | Sodium; serum, plasma or whole blood | 2212571
measurement during day -365 through 0   days relative to index | Blood count; hemoglobin (Hgb) | 2212643
measurement during day -365 through 0   days relative to index | Coagulation time; activated | 2212692
measurement during day -30 through 0 days   relative to index | Coagulation time; activated | 2212692
measurement during day -365 through 0   days relative to index | Platelet, aggregation (in vitro), each agent | 2212726
measurement during day -30 through 0 days   relative to index | Platelet, aggregation (in vitro), each agent | 2212726
measurement during day -30 through 0 days   relative to index | Prothrombin time | 2212731
measurement during day -365 through 0   days relative to index | Sedimentation rate, erythrocyte; automated | 2212737
measurement during day -30 through 0 days   relative to index | Sedimentation rate, erythrocyte; automated | 2212737
measurement during day -365 through 0   days relative to index | Thromboplastin time, partial (PTT); plasma or whole blood | 2212742
measurement during day -30 through 0 days   relative to index | Thromboplastin time, partial (PTT); plasma or whole blood | 2212742
procedure_occurrence during day -365   through 0 days relative to index | Antibody screen, RBC, each serum technique | 2212937
procedure_occurrence during day -30   through 0 days relative to index | Antibody screen, RBC, each serum technique | 2212937
procedure_occurrence during day -365   through 0 days relative to index | Blood typing, serologic; ABO | 2212945
procedure_occurrence during day -30   through 0 days relative to index | Blood typing, serologic; ABO | 2212945
procedure_occurrence during day -365   through 0 days relative to index | Blood typing, serologic; Rh (D) | 2212946
procedure_occurrence during day -30   through 0 days relative to index | Blood typing, serologic; Rh (D) | 2212946
measurement during day -365 through 0   days relative to index | Electrocardiogram, routine ECG with at least 12 leads; tracing   only, without interpretation and report | 2313815
measurement during day -30 through 0 days   relative to index | Electrocardiogram, routine ECG with at least 12 leads; tracing   only, without interpretation and report | 2313815
procedure_occurrence during day -365   through 0 days relative to index | Duplex scan of extracranial arteries; complete bilateral study | 2313975
procedure_occurrence during day -30   through 0 days relative to index | Duplex scan of extracranial arteries; complete bilateral study | 2313975
procedure_occurrence during day -365   through 0 days relative to index | Therapeutic, prophylactic, or diagnostic injection (specify   substance or drug); intravenous push, single or initial substance/drug | 2314215
procedure_occurrence during day -365   through 0 days relative to index | Emergency department visit for the evaluation and management   of a patient, which requires these 3 key components within the constraints   imposed by the urgency of the patient's clinical condition and/or mental   status | 2514437
procedure_occurrence during day -30   through 0 days relative to index | Emergency department visit for the evaluation and management   of a patient, which requires these 3 key components within the constraints   imposed by the urgency of the patient's clinical condition and/or mental   status | 2514437
device_exposure during day -365 through 0   days relative to index | Catheter, transluminal angioplasty, non-laser (may include   guidance, infusion/perfusion capability) | 2615752
device_exposure during day -30 through 0   days relative to index | Catheter, transluminal angioplasty, non-laser (may include   guidance, infusion/perfusion capability) | 2615752
device_exposure during day -365 through 0   days relative to index | Closure device, vascular (implantable/insertable) | 2615771
device_exposure during day -30 through 0   days relative to index | Closure device, vascular (implantable/insertable) | 2615771
device_exposure during day -365 through 0   days relative to index | Stent, non-coated/non-covered, with delivery system | 2615855
device_exposure during day -30 through 0   days relative to index | Stent, non-coated/non-covered, with delivery system | 2615855
device_exposure during day -365 through 0   days relative to index | Embolization protective system | 2615863
device_exposure during day -30 through 0   days relative to index | Embolization protective system | 2615863
device_exposure during day -365 through 0   days relative to index | Catheter, guiding (may include infusion/perfusion capability) | 2615865
device_exposure during day -30 through 0   days relative to index | Catheter, guiding (may include infusion/perfusion capability) | 2615865
device_exposure during day -365 through 0   days relative to index | Low osmolar contrast material, 300-399 mg/ml iodine   concentration, per ml | 2720870
device_exposure during day -30 through 0   days relative to index | Low osmolar contrast material, 300-399 mg/ml iodine   concentration, per ml | 2720870
condition_era group during day -365   through 0 days relative to index | Pain finding at anatomical site | 4132926
condition_era group during day -30   through 0 days relative to index | Pain finding at anatomical site | 4132926
condition_era group during day -365   through 0 days relative to index | Traumatic AND/OR non-traumatic brain injury | 4133611
condition_era group during day -30   through 0 days relative to index | Traumatic AND/OR non-traumatic brain injury | 4133611
device_exposure during day -365 through 0   days relative to index | Guide wire | 4159813
device_exposure during day -30 through 0   days relative to index | Guide wire | 4159813
condition_era group during day -365   through 0 days relative to index | Inflammatory disorder of musculoskeletal system | 4176946
condition_era group during day -30   through 0 days relative to index | Inflammatory disorder of musculoskeletal system | 4176946
condition_era group during day -365   through 0 days relative to index | Inflammation of specific body systems | 4178818
condition_era group during day -30   through 0 days relative to index | Inflammation of specific body systems | 4178818
condition_era group during day -365   through 0 days relative to index | Inflammation of specific body organs | 4181063
condition_era group during day -30   through 0 days relative to index | Inflammation of specific body organs | 4181063
condition_era group during day -365   through 0 days relative to index | Inflamed joint | 4182007
condition_era group during day -30   through 0 days relative to index | Inflamed joint | 4182007
condition_era group during day -365   through 0 days relative to index | Lesion of neck | 4185207
condition_era group during day -30   through 0 days relative to index | Lesion of neck | 4185207
condition_era group during day -365   through 0 days relative to index | Lesion of brain | 4200516
condition_era group during day -30   through 0 days relative to index | Lesion of brain | 4200516
condition_era group during day -365   through 0 days relative to index | Musculoskeletal instability | 4202835
condition_era group during day -30   through 0 days relative to index | Musculoskeletal instability | 4202835
observation during day -365 through 0   days relative to index | History of clinical finding in subject | 4214956
condition_era group during day -365   through 0 days relative to index | Instability of joint | 4285734
condition_era group during day -30   through 0 days relative to index | Instability of joint | 4285734
condition_era group during day -365   through 0 days relative to index | Arthritis | 4291025
condition_era group during day -30   through 0 days relative to index | Arthritis | 4291025
condition_era group during day -365   through 0 days relative to index | Pain | 4329041
condition_era group during day -30   through 0 days relative to index | Pain | 4329041
condition_era group during day -365   through 0 days relative to index | Spinal instability | 4345332
condition_era group during day -30   through 0 days relative to index | Spinal instability | 4345332
drug_era group during day -365 through 0   days relative to index | remifentanil | 19016749
drug_era group during day -30 through 0   days relative to index | remifentanil | 19016749
drug_era group during day 0 through 0   days relative to index | remifentanil | 19016749
drug_era group during day -365 through 0   days relative to index | DRUGS FOR FUNCTIONAL GASTROINTESTINAL DISORDERS | 21600127
drug_era group during day -30 through 0   days relative to index | DRUGS FOR FUNCTIONAL GASTROINTESTINAL DISORDERS | 21600127
drug_era group during day 0 through 0   days relative to index | DRUGS FOR FUNCTIONAL GASTROINTESTINAL DISORDERS | 21600127
drug_era group during day -365 through 0   days relative to index | BELLADONNA AND DERIVATIVES, PLAIN | 21600190
drug_era group during day -30 through 0   days relative to index | BELLADONNA AND DERIVATIVES, PLAIN | 21600190
drug_era group during day 0 through 0   days relative to index | BELLADONNA AND DERIVATIVES, PLAIN | 21600190
drug_era group during day -365 through 0   days relative to index | Belladonna alkaloids, semisynthetic, quaternary ammonium   compounds | 21600195
drug_era group during day -30 through 0   days relative to index | Belladonna alkaloids, semisynthetic, quaternary ammonium   compounds | 21600195
drug_era group during day 0 through 0   days relative to index | Belladonna alkaloids, semisynthetic, quaternary ammonium   compounds | 21600195
drug_era group during day -30 through 0   days relative to index | ANTIEMETICS AND ANTINAUSEANTS | 21600490
drug_era group during day 0 through 0   days relative to index | ANTIEMETICS AND ANTINAUSEANTS | 21600490
drug_era group during day -30 through 0   days relative to index | ANTIEMETICS AND ANTINAUSEANTS | 21600491
drug_era group during day 0 through 0   days relative to index | ANTIEMETICS AND ANTINAUSEANTS | 21600491
drug_era group during day -365 through 0   days relative to index | Other antiemetics | 21600498
drug_era group during day -30 through 0   days relative to index | Other antiemetics | 21600498
drug_era group during day 0 through 0   days relative to index | Other antiemetics | 21600498
drug_era group during day -365 through 0   days relative to index | MINERAL SUPPLEMENTS | 21600857
drug_era group during day -30 through 0   days relative to index | MINERAL SUPPLEMENTS | 21600857
drug_era group during day 0 through 0   days relative to index | MINERAL SUPPLEMENTS | 21600857
drug_era group during day -365 through 0   days relative to index | OTHER MINERAL SUPPLEMENTS | 21600884
drug_era group during day -30 through 0   days relative to index | OTHER MINERAL SUPPLEMENTS | 21600884
drug_era group during day 0 through 0   days relative to index | OTHER MINERAL SUPPLEMENTS | 21600884
drug_era group during day -365 through 0   days relative to index | Sodium | 21600885
drug_era group during day -30 through 0   days relative to index | Sodium | 21600885
drug_era group during day 0 through 0   days relative to index | Sodium | 21600885
drug_era group during day -365 through 0   days relative to index | Platelet aggregation inhibitors excl. heparin | 21600985
drug_era group during day -30 through 0   days relative to index | Platelet aggregation inhibitors excl. heparin | 21600985
drug_era group during day 0 through 0   days relative to index | Platelet aggregation inhibitors excl. heparin | 21600985
drug_era group during day -365 through 0   days relative to index | BLOOD SUBSTITUTES AND PERFUSION SOLUTIONS | 21601136
drug_era group during day -30 through 0   days relative to index | BLOOD SUBSTITUTES AND PERFUSION SOLUTIONS | 21601136
drug_era group during day 0 through 0   days relative to index | BLOOD SUBSTITUTES AND PERFUSION SOLUTIONS | 21601136
drug_era group during day -365 through 0   days relative to index | I.V. SOLUTIONS | 21601153
drug_era group during day -30 through 0   days relative to index | I.V. SOLUTIONS | 21601153
drug_era group during day 0 through 0   days relative to index | I.V. SOLUTIONS | 21601153
drug_era group during day -365 through 0   days relative to index | Solutions affecting the electrolyte balance | 21601160
drug_era group during day -30 through 0   days relative to index | Solutions affecting the electrolyte balance | 21601160
drug_era group during day 0 through 0   days relative to index | Solutions affecting the electrolyte balance | 21601160
drug_era group during day -365 through 0   days relative to index | IRRIGATING SOLUTIONS | 21601167
drug_era group during day -30 through 0   days relative to index | IRRIGATING SOLUTIONS | 21601167
drug_era group during day 0 through 0   days relative to index | IRRIGATING SOLUTIONS | 21601167
drug_era group during day -365 through 0   days relative to index | Salt solutions | 21601179
drug_era group during day -30 through 0   days relative to index | Salt solutions | 21601179
drug_era group during day 0 through 0   days relative to index | Salt solutions | 21601179
drug_era group during day -365 through 0   days relative to index | I.V. SOLUTION ADDITIVES | 21601194
drug_era group during day -30 through 0   days relative to index | I.V. SOLUTION ADDITIVES | 21601194
drug_era group during day 0 through 0   days relative to index | I.V. SOLUTION ADDITIVES | 21601194
drug_era group during day -365 through 0   days relative to index | Electrolyte solutions | 21601195
drug_era group during day -30 through 0   days relative to index | Electrolyte solutions | 21601195
drug_era group during day 0 through 0   days relative to index | Electrolyte solutions | 21601195
drug_era group during day -365 through 0   days relative to index | ANTINEOPLASTIC AND IMMUNOMODULATING AGENTS | 21601386
drug_era group during day -30 through 0   days relative to index | ANTINEOPLASTIC AND IMMUNOMODULATING AGENTS | 21601386
drug_era group during day 0 through 0   days relative to index | ANTINEOPLASTIC AND IMMUNOMODULATING AGENTS | 21601386
drug_era group during day -365 through 0   days relative to index | ANTINEOPLASTIC AGENTS | 21601387
drug_era group during day -30 through 0   days relative to index | ANTINEOPLASTIC AGENTS | 21601387
drug_era group during day 0 through 0   days relative to index | ANTINEOPLASTIC AGENTS | 21601387
drug_era group during day -365 through 0   days relative to index | ANTIMETABOLITES | 21601421
drug_era group during day -30 through 0   days relative to index | ANTIMETABOLITES | 21601421
drug_era group during day 0 through 0   days relative to index | ANTIMETABOLITES | 21601421
drug_era group during day -365 through 0   days relative to index | Folic acid analogues | 21601422
drug_era group during day -30 through 0   days relative to index | Folic acid analogues | 21601422
drug_era group during day 0 through 0   days relative to index | Folic acid analogues | 21601422
drug_era group during day -365 through 0   days relative to index | POTASSIUM-SPARING AGENTS | 21601532
drug_era group during day -30 through 0   days relative to index | POTASSIUM-SPARING AGENTS | 21601532
drug_era group during day 0 through 0   days relative to index | POTASSIUM-SPARING AGENTS | 21601532
drug_era group during day -365 through 0   days relative to index | Aldosterone antagonists | 21601533
drug_era group during day -30 through 0   days relative to index | Aldosterone antagonists | 21601533
drug_era group during day 0 through 0   days relative to index | Aldosterone antagonists | 21601533
drug_era group during day -365 through 0   days relative to index | BETA BLOCKING AGENTS | 21601664
drug_era group during day -30 through 0   days relative to index | BETA BLOCKING AGENTS | 21601664
drug_era group during day -365 through 0   days relative to index | BETA BLOCKING AGENTS | 21601665
drug_era group during day -30 through 0   days relative to index | BETA BLOCKING AGENTS | 21601665
drug_era group during day -365 through 0   days relative to index | SELECTIVE CALCIUM CHANNEL BLOCKERS WITH MAINLY VASCULAR   EFFECTS | 21601745
drug_era group during day -30 through 0   days relative to index | SELECTIVE CALCIUM CHANNEL BLOCKERS WITH MAINLY VASCULAR   EFFECTS | 21601745
drug_era group during day 0 through 0   days relative to index | SELECTIVE CALCIUM CHANNEL BLOCKERS WITH MAINLY VASCULAR   EFFECTS | 21601745
drug_era group during day -365 through 0   days relative to index | Dihydropyridine derivatives | 21601746
drug_era group during day -30 through 0   days relative to index | Dihydropyridine derivatives | 21601746
drug_era group during day 0 through 0   days relative to index | Dihydropyridine derivatives | 21601746
drug_era group during day -365 through 0   days relative to index | SYSTEMIC HORMONAL PREPARATIONS, EXCL. SEX HORMONES AND   INSULINS | 21602681
drug_era group during day -30 through 0   days relative to index | SYSTEMIC HORMONAL PREPARATIONS, EXCL. SEX HORMONES AND   INSULINS | 21602681
drug_era group during day 0 through 0   days relative to index | SYSTEMIC HORMONAL PREPARATIONS, EXCL. SEX HORMONES AND   INSULINS | 21602681
drug_era group during day -365 through 0   days relative to index | CORTICOSTEROIDS FOR SYSTEMIC USE | 21602722
drug_era group during day -30 through 0   days relative to index | CORTICOSTEROIDS FOR SYSTEMIC USE | 21602722
drug_era group during day 0 through 0   days relative to index | CORTICOSTEROIDS FOR SYSTEMIC USE | 21602722
drug_era group during day -365 through 0   days relative to index | CORTICOSTEROIDS FOR SYSTEMIC USE, PLAIN | 21602723
drug_era group during day -30 through 0   days relative to index | CORTICOSTEROIDS FOR SYSTEMIC USE, PLAIN | 21602723
drug_era group during day 0 through 0   days relative to index | CORTICOSTEROIDS FOR SYSTEMIC USE, PLAIN | 21602723
drug_era group during day -365 through 0   days relative to index | Glucocorticoids | 21602728
drug_era group during day -30 through 0   days relative to index | Glucocorticoids | 21602728
drug_era group during day 0 through 0   days relative to index | Glucocorticoids | 21602728
drug_era group during day -30 through 0   days relative to index | ANTIINFECTIVES FOR SYSTEMIC USE | 21602795
drug_era group during day 0 through 0   days relative to index | ANTIINFECTIVES FOR SYSTEMIC USE | 21602795
drug_era group during day -30 through 0   days relative to index | ANTIBACTERIALS FOR SYSTEMIC USE | 21602796
drug_era group during day 0 through 0   days relative to index | ANTIBACTERIALS FOR SYSTEMIC USE | 21602796
drug_era group during day -365 through 0   days relative to index | TETRACYCLINES | 21602797
drug_era group during day -30 through 0   days relative to index | TETRACYCLINES | 21602797
drug_era group during day 0 through 0   days relative to index | TETRACYCLINES | 21602797
drug_era group during day -365 through 0   days relative to index | Tetracyclines | 21602798
drug_era group during day -30 through 0   days relative to index | Tetracyclines | 21602798
drug_era group during day 0 through 0   days relative to index | Tetracyclines | 21602798
drug_era group during day -365 through 0   days relative to index | ANTIINFLAMMATORY AGENTS | 21603616
drug_era group during day -365 through 0   days relative to index | IMMUNOSUPPRESSANTS | 21603890
drug_era group during day -30 through 0   days relative to index | IMMUNOSUPPRESSANTS | 21603890
drug_era group during day 0 through 0   days relative to index | IMMUNOSUPPRESSANTS | 21603890
drug_era group during day -365 through 0   days relative to index | IMMUNOSUPPRESSANTS | 21603891
drug_era group during day -30 through 0   days relative to index | IMMUNOSUPPRESSANTS | 21603891
drug_era group during day 0 through 0   days relative to index | IMMUNOSUPPRESSANTS | 21603891
drug_era group during day -365 through 0   days relative to index | Other immunosuppressants | 21603926
drug_era group during day -30 through 0   days relative to index | Other immunosuppressants | 21603926
drug_era group during day 0 through 0   days relative to index | Other immunosuppressants | 21603926
drug_era group during day -30 through 0   days relative to index | MUSCLE RELAXANTS | 21604069
drug_era group during day 0 through 0   days relative to index | MUSCLE RELAXANTS | 21604069
drug_era group during day -30 through 0   days relative to index | MUSCLE RELAXANTS, CENTRALLY ACTING AGENTS | 21604091
drug_era group during day 0 through 0   days relative to index | MUSCLE RELAXANTS, CENTRALLY ACTING AGENTS | 21604091
drug_era group during day -365 through 0   days relative to index | Other centrally acting agents | 21604114
drug_era group during day -30 through 0   days relative to index | Other centrally acting agents | 21604114
drug_era group during day 0 through 0   days relative to index | Other centrally acting agents | 21604114
drug_era group during day -30 through 0   days relative to index | ANESTHETICS | 21604181
drug_era group during day 0 through 0   days relative to index | ANESTHETICS | 21604181
drug_era group during day -30 through 0   days relative to index | ANESTHETICS, GENERAL | 21604182
drug_era group during day 0 through 0   days relative to index | ANESTHETICS, GENERAL | 21604182
drug_era group during day -30 through 0   days relative to index | Opioid anesthetics | 21604200
drug_era group during day 0 through 0   days relative to index | Opioid anesthetics | 21604200
drug_era group during day -30 through 0   days relative to index | Other general anesthetics | 21604208
drug_era group during day 0 through 0   days relative to index | Other general anesthetics | 21604208
drug_era group during day -30 through 0   days relative to index | OPIOIDS | 21604254
drug_era group during day 0 through 0   days relative to index | OPIOIDS | 21604254
drug_era group during day -365 through 0   days relative to index | Natural opium alkaloids | 21604255
drug_era group during day -30 through 0   days relative to index | Natural opium alkaloids | 21604255
drug_era group during day 0 through 0   days relative to index | Natural opium alkaloids | 21604255
drug_era group during day -30 through 0   days relative to index | Phenylpiperidine derivatives | 21604269
drug_era group during day 0 through 0   days relative to index | Phenylpiperidine derivatives | 21604269
drug_era group during day -365 through 0   days relative to index | Other opioids | 21604296
drug_era group during day -30 through 0   days relative to index | Other opioids | 21604296
drug_era group during day 0 through 0   days relative to index | Other opioids | 21604296
drug_era group during day -365 through 0   days relative to index | Salicylic acid and derivatives | 21604304
drug_era group during day -30 through 0   days relative to index | Salicylic acid and derivatives | 21604304
drug_era group during day 0 through 0   days relative to index | Salicylic acid and derivatives | 21604304
drug_era group during day -365 through 0   days relative to index | ANTIPSYCHOTICS | 21604490
drug_era group during day -30 through 0   days relative to index | ANTIPSYCHOTICS | 21604490
drug_era group during day 0 through 0   days relative to index | ANTIPSYCHOTICS | 21604490
drug_era group during day -365 through 0   days relative to index | Butyrophenone derivatives | 21604515
drug_era group during day -30 through 0   days relative to index | Butyrophenone derivatives | 21604515
drug_era group during day 0 through 0   days relative to index | Butyrophenone derivatives | 21604515
drug_era group during day -365 through 0   days relative to index | ANXIOLYTICS | 21604564
drug_era group during day -30 through 0   days relative to index | ANXIOLYTICS | 21604564
drug_era group during day -365 through 0   days relative to index | Benzodiazepine derivatives | 21604565
drug_era group during day -30 through 0   days relative to index | Benzodiazepine derivatives | 21604565
drug_era group during day -365 through 0   days relative to index | HYPNOTICS AND SEDATIVES | 21604606
drug_era group during day -30 through 0   days relative to index | HYPNOTICS AND SEDATIVES | 21604606
drug_era group during day 0 through 0   days relative to index | HYPNOTICS AND SEDATIVES | 21604606
drug_era group during day -365 through 0   days relative to index | Other hypnotics and sedatives | 21604661
drug_era group during day -30 through 0   days relative to index | Other hypnotics and sedatives | 21604661
drug_era group during day 0 through 0   days relative to index | Other hypnotics and sedatives | 21604661
drug_era group during day -365 through 0   days relative to index | PSYCHOANALEPTICS | 21604685
drug_era group during day -30 through 0   days relative to index | PSYCHOANALEPTICS | 21604685
drug_era group during day 0 through 0   days relative to index | PSYCHOANALEPTICS | 21604685
drug_era group during day -365 through 0   days relative to index | ANTIDEPRESSANTS | 21604686
drug_era group during day -30 through 0   days relative to index | ANTIDEPRESSANTS | 21604686
drug_era group during day 0 through 0   days relative to index | ANTIDEPRESSANTS | 21604686
drug_era group during day -365 through 0   days relative to index | ANTIPARASITIC PRODUCTS, INSECTICIDES AND REPELLENTS | 21604847
drug_era group during day -30 through 0   days relative to index | ANTIPARASITIC PRODUCTS, INSECTICIDES AND REPELLENTS | 21604847
drug_era group during day 0 through 0   days relative to index | ANTIPARASITIC PRODUCTS, INSECTICIDES AND REPELLENTS | 21604847
drug_era group during day -365 through 0   days relative to index | ANTIPROTOZOALS | 21604848
drug_era group during day -30 through 0   days relative to index | ANTIPROTOZOALS | 21604848
drug_era group during day 0 through 0   days relative to index | ANTIPROTOZOALS | 21604848
drug_era group during day -365 through 0   days relative to index | ANTIMALARIALS | 21604886
drug_era group during day -30 through 0   days relative to index | ANTIMALARIALS | 21604886
drug_era group during day 0 through 0   days relative to index | ANTIMALARIALS | 21604886
drug_era group during day -365 through 0   days relative to index | Aminoquinolines | 21604887
drug_era group during day -30 through 0   days relative to index | Aminoquinolines | 21604887
drug_era group during day 0 through 0   days relative to index | Aminoquinolines | 21604887
drug_era group during day -30 through 0   days relative to index | NASAL PREPARATIONS | 21605008
drug_era group during day 0 through 0   days relative to index | NASAL PREPARATIONS | 21605008
drug_era group during day -30 through 0   days relative to index | DECONGESTANTS AND OTHER NASAL PREPARATIONS FOR TOPICAL USE | 21605009
drug_era group during day 0 through 0   days relative to index | DECONGESTANTS AND OTHER NASAL PREPARATIONS FOR TOPICAL USE | 21605009
drug_era group during day -365 through 0   days relative to index | Sympathomimetics, plain | 21605010
drug_era group during day -30 through 0   days relative to index | Sympathomimetics, plain | 21605010
drug_era group during day 0 through 0   days relative to index | Sympathomimetics, plain | 21605010
drug_era group during day -365 through 0   days relative to index | MYDRIATICS AND CYCLOPLEGICS | 21605058
drug_era group during day -30 through 0   days relative to index | MYDRIATICS AND CYCLOPLEGICS | 21605058
drug_era group during day 0 through 0   days relative to index | MYDRIATICS AND CYCLOPLEGICS | 21605058
drug_era group during day -365 through 0   days relative to index | Sympathomimetics excl. antiglaucoma preparations | 21605067
drug_era group during day -30 through 0   days relative to index | Sympathomimetics excl. antiglaucoma preparations | 21605067
drug_era group during day 0 through 0   days relative to index | Sympathomimetics excl. antiglaucoma preparations | 21605067
observation during day -365 through 0   days relative to index | Hospital outpatient clinic visit for assessment and management   of a patient | 44786391
observation during day -30 through 0 days   relative to index | Hospital outpatient clinic visit for assessment and management   of a patient | 44786391

Some of these covariates appear to be artifacts of being an in-patient centric database evaluating an outcome that is also in-patient centric.

Sample size is very low which may exacerbate this correlation. Will likely exclude this database from the analysis.

**Question:** Should we update the RCT package covariates to exclude?

**Comment by rw2646** [comment]
Some of these co-variates are disease/RA-related, some are in-patient admission related.  
Given that we see a high correlation of admission-related codes, it is likely the index date coincide with in-patient admission date, which means the first occurrence of drug of interest was the first documentation in the system, rather than initiation of the drug.  Agree with Kristin that we probably should not include this database for the analysis.

**Comment by kmkostka** [comment]
Agreed. We will not use this data source for either design.
